### ISSUE TITLE
Babel support

### ISSUE THREAD

**Issue by jbezos** [KurdishXeLaTeX/Support#1]
I've just came across to your project and I think it could be a nice idea to improve the current support in [babel](https://github.com/latex3/babel) too, for both XeLaTeX and LuaLaTeX. If I prepare some preliminary `ini` files (see examples [here](https://github.com/latex3/babel/tree/master/locale)), could you have a look at them, as well as make suggestions?

**Edit.** For sorani you can see https://github.com/latex3/babel/tree/master/locale/ckb .

**Comment by jbezos** [comment]
Here is a short example with the current locale for Sorani and `lualatex`:
```
\documentclass{article}

\usepackage[bidi=basic]{babel}

\babelprovide[import, main, maparabic]{centralkurdish}
\babelprovide[onchar=ids fonts]{polytonicgreek}
\babelprovide[onchar=ids fonts]{english}

\babelfont{rm}{Yas}
\babelfont[polytonicgreek, english]{rm}{Times New Roman}

\begin{document}

\section{\TeX چییە؟}

\TeX{} بۆ یەکەم جار لە ساڵی ١٩٧٨ لە لایەنی زانا و بلیمەتی کۆمپیوتەر
دۆناڵد کنووس (Donald Knuth) ەوە ساز کرا. \TeX{} لە سەر ئەو بۆچوونەدا
پێکهاتووە کە نووسەر دەبێ کاری نووسین بکا نەک ڕازاندنەوەی دەق. واتە، بۆ
نووسەری بەڵگەیەک دەبێ ئەو ئامێرانە دابین کرابێ کە بتوانێ بە هەموو
پێداویستییەکانی لە نووسیندا بگا، بگرە بۆ نووسینی فرمووڵێکی بیرکاری بێ
یان هاوکێشەیەکی کیمیایی یان پارچە شیعرێک. بۆیەش، لە نێو ئاکادیمیا و ئەو
کەسانه کە بە لێهاتوویی لە سەر بابەتێکی زانستی دەنووسن لە \TeX{} زۆر بە
بەربڵاوی کەڵک وەردەگیردرێ. وشەی \TeX{} لە وشەی یۆنانی \textit{τέχνη}
یەوە دێ کە بە مانای هونەرە. لە بەر ئەوەی فۆنیمی χ لە کوردی و زۆر زماندا
بەرانبەرێکی نییە، دەتوانین لە کوردی بڵەین \textit{تێک} یان
\textit{تێخ}.

\paragraph{تایبەتمەندییەکانی \TeX} بە کورتی، لە تایبەتیمەندییە هەرە
گرینگەکانی تێک ئەمانەن:
 
\begin{itemize}
\item نووسینی گۆڤار، کتێب، ڕاپۆرتی تەکنیکی و سڵایدی ئامادەکاری
\item بەڕێوە بردنی بەڵگە گەورەکان کە زۆر بەش و بەند و سەرچاوەیان تێدایە
\item نووسینەوەی فرمووڵە پڕ وردەکارییەکان لە بیرکاریدا
\item سازکردنی ئۆتۆماتیکی سەرچاوەکان
\item بە ئاسانی کەڵک وەرگرتن لە وێنە و دیاگرام
\item گۆڕانەوە بە شێوەکانی دیکەی نیشان دانی دەق وەکوو HTML
\end{itemize}

\end{document}
```

**Comment by sinaahmadi** [comment]
Hi @jbezos ,

Thanks for your suggestion. It sounds good. I should be able to work on it and test it in the coming weeks. I will keep you posted.

Thanks again for your interest 🙂

**Comment by sinaahmadi** [comment]
Hi @jbezos ,

I have created the required files to update Kurdish on Babel. I just saw that you have modified some of the files and also included the Latin option for Sorani. I should have kept you posted earlier to avoid doing the same thing in parallel. My bad!

I was thinking of following the same configuration of Polyglossia with respect to the variants and scripts for Kurmanji and Sorani. But apparently, the [Kurmanji dialect](http://ftp.heanet.ie/mirrors/ctan.org/tex/macros/latex/contrib/babel-contrib/kurmanji/kurmanji.pdf) is not included in LuaLaTex but in LaTeX in Babel. If that's the case, I think it would be better to keep using `centeralkurdish` for Sorani without further adding another dialect. 

One remark is regarding the Latin script. I am not able to compile your latest commit with the Latin script. If you can kindly check it out and let me know if I should be using something else rather than `\babelprovide[import,main]{centralkurdish-latn}`. My `ckb` folder looks like this:

```
├── babel-centralkurdish-arab.tex
├── babel-centralkurdish-arabic.tex
├── babel-centralkurdish-latin.tex
├── babel-centralkurdish-latn.tex
├── babel-centralkurdish.tex
├── babel-ckb-Arab.ini
├── babel-ckb-Latn.ini
├── babel-ckb.ini
├── babel-sorani.tex
```

Thanks.

**Comment by jbezos** [comment]
Thank you very much for your contribution. I'll have a look at it and I'll improve what I've done so far (the files I've uploaded are still development versions).

Currently I'm working ‘transversally’ (so that babel will become a ‘provider’ of tools, too, in addition to the old good model based on closed language files), and I'd like to take this opportunity to write some code for alternative date formats in `ini` files (eg, with izafet).

The Kurmanji style was devised mainly for `pdftex`, although it should work with `lualatex` and `xelatex` (not tested). I  don't remember the reason I didn't include the `ini` files for Kurmanji at the time, but I think I had some doubts about the data provided by the Unicode CLDR.

**Comment by sinaahmadi** [comment]
I will go through the data and will create a pull request to merge it.

But would you please confirm if the following header is correct for using Latin for CKB?

```
\documentclass{article}

\usepackage{babel}

\babelprovide[import,main]{centralkurdish-latn}
```
I am not able to compile with the Latin script with your latest modifications.

**Comment by jbezos** [comment]
It should, but I haven't created the file `babel-centralkurdish-latn.tex` yet, only `babel-centralkurdish-latin.tex`. For testing you may use the latter, because the file contents are the same.

**Comment by jbezos** [comment]
A little question before committing a new development version in a couple of days, with some fixes. There are two date variants in Kurmanji, the main one and the inflected version.  What would be the best name to identify the latter? According to the manual it is used in the head of letters, so a possible name would be `letter`, but I'm convinced there is a better name.

**Comment by sinaahmadi** [comment]
Hi Javier,

Would you please take a look at these files: [https://github.com/KurdishXeLaTeX/Support/tree/master/styles](https://github.com/KurdishXeLaTeX/Support/tree/master/styles). I have added further information and corrected a few of the glosses. 

Regarding the calendar, for the inflected one, following the Hungarian configuration, Polyglossia uses `\ontoday`, as you know. How do you find `IzafaCalendar`? The same issue exists for Sorani.

Having said that, I have defined two calendars, one Kurdish and the other one Georgian.

Please let me know if you'd need any further assistance or testing.

**Comment by jbezos** [comment]
A new babel version is now in CTAN. I hope I've done things well. Please, let me know if there are any mistakes or omissions.

**Comment by sinaahmadi** [comment]
Thanks @jbezos!
